flowchart TD 
subgraph SA ["API"]
   Catalog["Catálogo<br> listar e buscar livros"]
    Loan["Empréstimos<br> emprestar e devolver livros"]
    Notification["Notificações<br> monitora e notifica usuário sobre prazo "]
end

Email["Disparador de e-mails"]

Loan -->|consulta| Catalog
Loan -->|aciona| Notification
Notification -->|chama| Email