flowchart TD 

User(["Usuário"])
Librarian(["Bibliotecário"])

subgraph SB["Sistema da biblioteca"]
  App["App do Usuário"]
  Backoffice["App do Bibliotecário"]
  Server["API"]
  DB[("Banco de dados")]

  end

  Email["Serviço de email"]

  User -->|Pesquisa e empresta livros| App
  Librarian -->|Gerencia livros e empréstimos| Backoffice
  App -->|Chama API| Server
  Backoffice -->|Chama API| Server
  Server -->|Lê e grava dados| DB
  Server --->|Monitora e notifica o prazo| Email