 title Sistema de Vendas - Diagrama de Contêineres

    Person(vendedor, "Vendedor")
    Person(admin, "Administrador")
    Person(estoque, "Time de Estoque")

    System_Boundary(sistema, "Sistema de Vendas") {

        Container(interface, "Interface", "Web", "Interface utilizada pelos usuários")

        Container(pedidos, "Pedidos", "Backend", "Registra e consulta pedidos")

        Container(produtos, "Produtos", "Backend", "Cadastra e remove produtos")

        Container(estoqueSistema, "Estoque", "Backend", "Controla entradas e saídas")

        ContainerDb(banco, "Banco de Dados", "MySQL", "Armazena os dados do sistema")
    }

    Rel(vendedor, interface, "Acessa")
    Rel(admin, interface, "Acessa")
    Rel(estoque, interface, "Acessa")

    Rel(interface, pedidos, "Utiliza")
    Rel(interface, produtos, "Utiliza")
    Rel(interface, estoqueSistema, "Utiliza")

    Rel(pedidos, banco, "Salva dados")
    Rel(produtos, banco, "Salva dados")
    Rel(estoqueSistema, banco, "Salva dados")